travis:
  secure:
    BINSTAR_TOKEN: ITZArnf6ixzdZgLOJUgvRiuTSGYgN9x2r+ZQbZHCy8+8nWzIUQUrK9oRsc8ApxsG46N4mDJqimjcj7/42wswy8wuvzGx0e07ZVMRAsIPButckh3LhY5wvUnEZ2h0GjitBSsr5X9oJT0Bo/AQrD0kNFapR5huH0LgOiftU6Jq0PWNMQq4yf+Yf6Dfra3mkYMwTgrId2NajRKuaYhjuPDQHMVf71X6PiWm1uPpQzvlVktxq30ltD17w6gom/suYnZF8CyySaVmZnrO3QGG1Fw1Ha8WeuTKdRMb5Puj4LXoK/cPgYYayxwbaInD/iSRIONObOz5lS7PNO5c+UvWICJd5PfxkYl3E1BrvcS3SdOEOzU51oZizI6wL/ugp5IvDMHt6gRPNdN9tetUXeLD3bw1moLcbVVvGYqwhJzuBkVRaoNi2imNHR9BKVznNjVMhcETVobeQDAzz4WzOI86e8q6PMPged3P7IkgvD6WMVc6aAkT0tbqCNmWYOESoUfL+ACW+ofU2HMq81/dG1pb/HdzKOeFDYcKekf4x1ZvAqrI/Ulp6iVnt+Sv3wLrmhNWQAdv8TNQUXtYR0qI4oJCeKX/98JRkHqlkAeYNDfTtAd5enI6L3w+0dd4W/Ma3L480dWIZvev091pUx99Huw5TWhscaWEamPwqef/3WLV9Ih/Tks=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
