travis:
  secure:
    BINSTAR_TOKEN: l18dFj6iAzScQGXg0XoYWPxvf04nlkkJ9Ru+LimgUiza5y4KF4v1BxsxjzBUubYhC8wCBtK97pmKVTzrt9CulRUol7BwNbuFg3OqhBJ1NvcIw74cDCNNwXQk2o6RVHwfp16QUttG/5JlH4zyTDPPVTgRJlNY9fA4ts5DYpl54hRPMQ6B+wp7lqU4adnkkhHG2rOIg2fEazeJbGisHXanXUln5y9MbQNCXDdn9GWBDjKuOT4tJEM5NIlVoGitEoLJysDDUK3Sqh0FVfv2OSU4yGc6gEMU8/aeBlJIhVvAVdSz3TWVmF69XI4VWJP30KzKRDPJaTbgEv+r8fYm2Ps1u/x6ZKXOLsYHMfd/0tppzHeNntsOTeJZp/agE49rd92puhbXXHbJo3klZYyBDuWFe/OE5iQ/hvc/ZELVOqwHRsUT/RbqdV9zj/1ybC71JrFc9dMde3HPOQ8KY9U6kHenVHwsz1DUujR25596Sk39y6O8RgOUk/p8OWUxCQACLXqcxwiVDRxeGTxNihts/mkQdbBWdEx5BDnO2kEB/UYgCNEIqDtN1bu/qcl1XmaGW0e+3iGpUT3giWPgAPRC3d0vDDqLtxpA9EIN7fqlzU7h4H/nl8iZVH3EMXVwmH2koSVvbhwN/xi0NoRqyw1teAkMc9GOM3KR+AdRg7uTH+uk9F8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
